drop table if exists academy_award ;
create table academy_award (
   id integer generated by default as identity (start with 1),
    additionalInfo varchar(500),
    category varchar(255),
    nominee varchar(1000),
    edition integer,
    won boolean,
    year varchar(10),
    primary key (id)
)
create table api_key (
   id integer generated by default as identity (start with 1),
    createdOn timestamp ,
    email varchar(255),
    expireDays integer not null,
    key varchar(255),
    primary key (id)
)
